title: Ariwalagan Dhilshan
logo: assets/img/Ariwalagan_Dhilshan02.png
description: "Welcome to my portfolio!"
github_repo_url: "https://github.com/Dhilshan2000/portfolio"
show_downloads: true 
theme: jekyll-theme-minimal







