title: Ariwalagan Dhilshan
logo: assets/img/Ariwalagan_Dhilshan02.png
description: "Welcome to my Portfolio!"
github_repo_url: "https://dhilshan2000.github.io/portfolio/"
show_downloads: true 
theme: jekyll-theme-minimal







